### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by basnijholt**
I created a function that plots 2D band structures.

It uses `wraparound`, therefore real-space Hamiltonians can be used.

Check the material of week 4 for example uses.

### CODE REVIEW

**Comment by akhmerov** [comment]
I'm wondering if it's better to instead subclass `SimpleNamespace`, and define `__iadd__` method, so that instead of `update(p, p1)` we'd write `p += p1`, @basnijholt what do you think?

**Comment by basnijholt** [comment]
Now `update` can be used to change multiple parameters, with `__iadd__` you would only be able to change one variable per iteration.

**Comment by akhmerov** [comment]
Why? The thing that you add is a different namespace or a dict. If I just wanted to update a single attribute, I'd use `p.attribute = value`.

**Comment by basnijholt** [comment]
How would you do this:

```
holoviews.HoloMap({t, mu: spectrum(sys, update(p, mu=mu, t=t)) for t in ts for mu in mus})
```

**Comment by akhmerov** [comment]
Yes, `__iadd__` isn't designed for inline updates. For that I'd implement an `update` method in a subclass.

**Comment by basnijholt** [comment]
I improved `spectrum` and `plot_bands_2d`, I would like to implement the changes in both `w1` and `w2`.

**Pull request merged**
