### PR TITLE
Plotting

### PR DESCRIPTION
**Pull request by akhmerov**
New version of #125, with more systematic review ;-)

### CODE REVIEW

**Comment by akhmerov** [comment]
I see one of the bands missing in QWZ dispersion:

image

**Comment by akhmerov** [comment]
Further: the grid lines on the surface are now too dark, giving the plots a somewhat unclean look. Compare with the old version:

image

That is achieved by making the grids more dense and less dark.

**Comment by akhmerov** [comment]
Is `functions.h_k` still used? If it is, it's better to rewrite its insides using `wraparound`, and to make it also applicable to general dimensionality. Also the code related to the reciprocal lattice can go there.

**Comment by akhmerov** [comment]
OK, I've now rewritten `code/functions` to be somewhat more general. I'll now rework w1/1D to use.

**Comment by basnijholt** [comment]
Setting `xticks` with a number doens't work.

**Comment by akhmerov** [comment]
What should it be if it's a number?

**Comment by akhmerov** [comment]
Also if you know how to fix that: go ahead.

**Comment by basnijholt** [comment]
Never mind, I had already deleted the comment. I made a mistake myself, I wasn’t even using `spectrum`, but a holoviews function.

On Mon, 15 Feb 2016 at 16:38 Anton Akhmerov

<
mailto:Anton Akhmerov <notifications@github.com>
> wrote:

What should it be if it's a number?

**Pull request merged**
