### PR TITLE
Insert newline at end if missing

### PR DESCRIPTION
**Pull request by torosdahl**
Carbon copy of http://unix.stackexchange.com/questions/31947/how-to-add-a-newline-to-the-end-of-a-file

I'm not sure if this actually fixes the issue, as this is presently not a problem in any notebook for me. However, with this modification, the filter still runs on my laptop, so presumably the sed command finds the temporary notebook.

### CODE REVIEW

**Comment by akhmerov** [comment]
Does this fix the filter problem?

**Comment by basnijholt** [comment]
That is literally what I tried and unfortunately it doesn't solve the
problem.

**Comment by torosdahl** [comment]
But does the filter run for you with this modification? In the chat, you mentioned that sed didn't find the temporary file, which does not seem to be the case on my laptop.

**Comment by basnijholt** [comment]
With the extra line added in 0b011a9 the problem is fixed.

**Pull request merged**
