### PR TITLE
Holoviews w2

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by bernardvanheck** [comment]
Parameters in In[6] of nanowire.ipynb seem wrong; the band structure is gapped contrary to what it should be.

**Comment by akhmerov** [comment]
@basnijholt The first plot in `signatures.ipynb` misses a legend, can you please add it?

**Comment by akhmerov** [comment]
Everything looks OK now, waiting for the legend.

**Comment by jaysau** [comment]
Hey guys - sorry just got back from California - but here are my somewhat minor comments on the signatures notebook: (1) maybe we could be more specific about "conductance quantum:" and say that it is (apart from numerical factors) unique combination of fundamental constants with the dimensions of conductance (2) I don't see the relevance of the comment on Majorana "leaking" into the metal to the rest of the discussion (3) I don't agree with the comment at the end of the subsection "Quantization of the Majorana resonance" about having to go beyond the cartoon. In the double barrier picture perfect Andreev reflection in the Majorana case is simply the "standard" perfect resonant transmission from any quantum mechanics textbook - the discussion in the next section isn't key. I would say that the next section is needed to generalize the picture to include the role of the rest of the wire (apart from the Majorana) and multiplechannels. Ultimately, let's us write the topological invariant. (4)  I propose adding the word "fractional" to the title of the subsection "Detecting the fermion parity..." This is because I can guess that much of our readership would have heard of the phrase the fractional Josephson effect.

**Pull request merged**
