### PR TITLE
Week11

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by akhmerov** [comment]
We still need to fix the crystalline TI.

**Comment by akhmerov** [comment]
In `cti.ipynb` both `nanowire_chains` and `stacked_qwz` are used exactly once. I think this would make it better to move the functions exactly to the cells where they are used; what do you say?

**Comment by basnijholt** [comment]
I agree.

**Comment by akhmerov** [comment]
Same thing holds for `nanowire_chain` inside `floquet.ipynb`. Finally I suggest to rename `get_evolution_operator` into `evolution_operator` and add a docstring that explicitly says that each Hamiltonian is applied for the same fraction of a period.

The text changes look quite good!

**Comment by basnijholt** [comment]
Both fixed.

**Comment by akhmerov** [comment]
Thanks!

**Pull request merged**
