### PR TITLE
Week3

### PR DESCRIPTION
**Pull request by basnijholt**

### CODE REVIEW

**Comment by torosdahl** [comment]
I've looked at the figures and text, everything looks good to me. Shall we merge?

**Comment by basnijholt** [comment]
I agree.

On Mon, 22 Feb 2016 at 08:49 "Tómas Örn Rosdahl"

<
mailto:
> wrote:

I've looked at the figures and text, everything looks good to me. Shall we merge?

**Comment by akhmerov** [comment]
Did you try also uploading to the sandbox course on edge?

**Comment by akhmerov** [comment]
I've found a few minor things with code, fixing.

**Pull request merged**
