### PR TITLE
Week4

### PR DESCRIPTION
**Pull request by akhmerov**

### CODE REVIEW

**Comment by akhmerov** [comment]
I've done another proofread after @torosdahl, everything looks good (hence merging directly). BTW @torosdahl don't hesitate to make larger changes to formulations, sometimes the wording is by no means eloquent.

**Comment by akhmerov** [comment]
Another remark about the code: please add docstrings to non-standard functions!

**Comment by basnijholt** [comment]
Which functions do you think require a doc-string?

**Comment by akhmerov** [comment]
In w4 only Berry curvature.

**Comment by akhmerov** [comment]
Oh, another remark: when making a week's branch, set the release date in `scripts/release_dates`. This makes it visible by the converter.

**Comment by basnijholt** [comment]
That one has a doc-string. Do you mean to elaborate more on the calculation?

**Comment by akhmerov** [comment]
It has a docstring because I added it :)

**Comment by basnijholt** [comment]
Ah, haha. I'm recompiling the Binder image BTW.

**Pull request merged**
