### PR TITLE
W5 qshe

### PR DESCRIPTION
**Pull request by basnijholt**
Needs to be PEP8'ified

update: fixed in fermion_parity_pump.ipynb

### CODE REVIEW

**Comment by basnijholt** [comment]
```
def hopx(site1, site2, par):
    A, B, D, M = par.A/2, par.B, par.D, par.M
    return B * pauli.s0sz + D * pauli.s0s0 + 1j * A * pauli.szsx
```
this unpacking of variables is not needed

**Comment by basnijholt** [comment]
```
def hopping_x(site1, site2, par):
        xt, yt = site1.pos
        xs, ys = site2.pos
        return hopx(site1,site2,par) * np.exp(-0.5j * par.Bz * (xt - xs) * (yt + ys))
```

everywhere else in the course we use `p` instead of `par` and `x1 y1` instead of `xt, yt`

**Comment by basnijholt** [comment]
```
    xlims, ylims = slice(-0.2, np.pi+0.2), slice(-np.pi-0.2, np.pi+0.2)
    ticks = {'xticks': [(0, '0'), (np.pi, '$\pi$')], 'yticks': [(-np.pi, '$-\pi$'), (0, '0'), (np.pi, '$\pi$')]}
    return plot.relabel('Winding', depth=1)[xlims, ylims](plot=ticks)
```

instead of using the slides, a nicer syntax is `return plot[-0.2:np.pi+0.2, -np.pi-0.2, np.pi+0.2]`

**Comment by basnijholt** [comment]
these parameters `ez_x=0.0, ez_y=0.0, eze_z=0.0, ezh_z=0.0` are always zero, so maybe it's nice to remove them from the functions.

**Comment by basnijholt** [comment]
`if w == 'None':` should not be `'None'` as a string but rather just `if w is None:`

**Comment by basnijholt** [comment]
```
    sys[lat(0,0)] = lambda site, par: onsite(site,par)
    sys[lat(0,w-1)] = lambda site, par: onsite(site,par)
```

can just be
```
    sys[lat(0,0)] = onsite
    sys[lat(0,w-1)] = onsite
```

**Comment by basnijholt** [comment]
here you could list comprehensions and I think the lists `det` and `pfaff` make it confusing here as the variable `smat` that is added, is overwritten twice.

```
    pfaff = []
    det = []
    p.ky = 0.0
    smat = kwant.smatrix(fsys, energy=0.0, args=[p]).data
    #since we get relatively large numerical errors we project the matrix on the space of antisymmetric matrices
    smat = 0.5 * (smat - smat.T)
    pfaff.append(pf.pfaffian(smat))

    ks = np.linspace(0.0, np.pi, 50)
    for p.ky in ks:
        smat = kwant.smatrix(fsys, energy=0.0, args=[p]).data
        det.append(np.linalg.det(smat))
    det = np.array(det)
    p.ky = np.pi
    smat = kwant.smatrix(fsys, energy=0.0, args=[p]).data
    #since we get relatively large numerical errors we project the matrix on the space of antisymmetric matrices
    smat = 0.5 * (smat - smat.T)
    pfaff.append(pf.pfaffian(smat))
```

**Comment by basnijholt** [comment]
The parameters `kx=0, ky=0` that are defined in the `SimpleNamespace`s are not used.

**Comment by basnijholt** [comment]
In `fermion_parity_pump.ipynb` still need to fix size issue
download

**Comment by akhmerov** [comment]
What's the issue?

**Comment by basnijholt** [comment]
The screenshot that I attached with that post. They have different aspect ratios.

**Comment by akhmerov** [comment]
Ah, I see.

**Comment by akhmerov** [comment]
Included fix for #34.

**Pull request merged**
