### PR TITLE
Code cell error handling in cachedoutput preprocessor

### PR DESCRIPTION
**Pull request by torosdahl**
Related to #117. Changed preprocess_cell in the cache preprocessor, to match the handling of cell execution errors in ExecutePreprocessor.

### CODE REVIEW

**Comment by akhmerov** [comment]
I'm wondering if this is the behavior we want. This would, as far as I understand, leave a complete notebook not executed by the preprocessor. Wouldn't we prefer only the failed cells to be not executed?

On the other hand, if the error message is clearly printed, it should also be fine. Did you check if it works if you introduce an error in a notebook?

**Comment by torosdahl** [comment]
I checked. It also works if there is an error in the first cell.

You're right, presently, no output is printed if an error is encountered in any cell. If an error is encountered in a cell, the contents of the cell are printed, along with the type of error and error message.

**Comment by torosdahl** [comment]
But I think it should be easy to modify to have the behaviour you suggested. Shall I give it a shot?

**Comment by akhmerov** [comment]
By all means! Just to go sure, I imagine the correct behavior is a message to stderr informing the user that some evaluations failed while the failed cells are left without output at all.

**Comment by torosdahl** [comment]
I believe this will do the trick. If an error is encountered, the user is informed and the filter moves on to the next cell without storing output, unless the current cell is a setup cell. In this case, the script informs the user and terminates without storing output.

I tested both cases, and it seems to work.

**Comment by torosdahl** [comment]
.. and now the failed cells are also left without output in the notebook.

**Comment by irfanphy** [comment]
tested and works fine. closes issue 117

**Pull request merged**
